### ISSUE TITLE
Error when tried to load MoNET in RStudio

### ISSUE THREAD

**Issue by froz9** [Feng-GitHub-Feng/MoNET#1]
Hello, 

I am using R 4.0.2. I manually installed MoNET, but after installing it, when I tried to load the library, I got this error message:

Error: package or namespace load failed for ‘MoNET’:
 package ‘MoNET’ was installed before R 4.0.0: please re-install it

I understand that the ZIP file is a pre-built binary package for use on Windows, not a source package. And I want to know if you to build them again for R 4.0? or If you can provide me the actual source -the .tar.gz file that appears as deleted.

Thank you in advance. Best regards.

**Comment by Feng-GitHub-Feng** [comment]
Hi,

Thanks for your interest in MoNET.

MoNET was built using R 3.5.1. The reason for the error may be that you are using a higher version R 4.0.2. You can try install R 3.5.1 and re-install the package. If you are interested in the soure file, please download it from https://github.com/JW-Yan/MONET. 

Hope this will help you. Best regards.

**Comment by froz9** [comment]
Hi Feng,

Thank you for your prompt response. I downloaded R 3.5.1, and I'm already testing MoNET. I'm excited to see the results, and I hope to introduce your Package to my work.

Thank you so much.
